//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02.CLIWEB.ConversionServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConversionServiceReference.IConversionService")]
    public interface IConversionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/Login", ReplyAction="http://tempuri.org/IConversionService/LoginResponse")]
        bool Login(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/Login", ReplyAction="http://tempuri.org/IConversionService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/MetroAPie", ReplyAction="http://tempuri.org/IConversionService/MetroAPieResponse")]
        double MetroAPie(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/MetroAPie", ReplyAction="http://tempuri.org/IConversionService/MetroAPieResponse")]
        System.Threading.Tasks.Task<double> MetroAPieAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/KilometroAMilla", ReplyAction="http://tempuri.org/IConversionService/KilometroAMillaResponse")]
        double KilometroAMilla(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/KilometroAMilla", ReplyAction="http://tempuri.org/IConversionService/KilometroAMillaResponse")]
        System.Threading.Tasks.Task<double> KilometroAMillaAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CentimetroAPulgada", ReplyAction="http://tempuri.org/IConversionService/CentimetroAPulgadaResponse")]
        double CentimetroAPulgada(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CentimetroAPulgada", ReplyAction="http://tempuri.org/IConversionService/CentimetroAPulgadaResponse")]
        System.Threading.Tasks.Task<double> CentimetroAPulgadaAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/PulgadaACentimetro", ReplyAction="http://tempuri.org/IConversionService/PulgadaACentimetroResponse")]
        double PulgadaACentimetro(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/PulgadaACentimetro", ReplyAction="http://tempuri.org/IConversionService/PulgadaACentimetroResponse")]
        System.Threading.Tasks.Task<double> PulgadaACentimetroAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/PieAMetro", ReplyAction="http://tempuri.org/IConversionService/PieAMetroResponse")]
        double PieAMetro(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/PieAMetro", ReplyAction="http://tempuri.org/IConversionService/PieAMetroResponse")]
        System.Threading.Tasks.Task<double> PieAMetroAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/KilogramoALibra", ReplyAction="http://tempuri.org/IConversionService/KilogramoALibraResponse")]
        double KilogramoALibra(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/KilogramoALibra", ReplyAction="http://tempuri.org/IConversionService/KilogramoALibraResponse")]
        System.Threading.Tasks.Task<double> KilogramoALibraAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/GramoAOnza", ReplyAction="http://tempuri.org/IConversionService/GramoAOnzaResponse")]
        double GramoAOnza(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/GramoAOnza", ReplyAction="http://tempuri.org/IConversionService/GramoAOnzaResponse")]
        System.Threading.Tasks.Task<double> GramoAOnzaAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/ToneladaAKilogramo", ReplyAction="http://tempuri.org/IConversionService/ToneladaAKilogramoResponse")]
        double ToneladaAKilogramo(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/ToneladaAKilogramo", ReplyAction="http://tempuri.org/IConversionService/ToneladaAKilogramoResponse")]
        System.Threading.Tasks.Task<double> ToneladaAKilogramoAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/LibraAKilogramo", ReplyAction="http://tempuri.org/IConversionService/LibraAKilogramoResponse")]
        double LibraAKilogramo(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/LibraAKilogramo", ReplyAction="http://tempuri.org/IConversionService/LibraAKilogramoResponse")]
        System.Threading.Tasks.Task<double> LibraAKilogramoAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/OnzaAGramo", ReplyAction="http://tempuri.org/IConversionService/OnzaAGramoResponse")]
        double OnzaAGramo(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/OnzaAGramo", ReplyAction="http://tempuri.org/IConversionService/OnzaAGramoResponse")]
        System.Threading.Tasks.Task<double> OnzaAGramoAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/IConversionService/CelsiusAFahrenheitResponse")]
        double CelsiusAFahrenheit(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/IConversionService/CelsiusAFahrenheitResponse")]
        System.Threading.Tasks.Task<double> CelsiusAFahrenheitAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusAKelvin", ReplyAction="http://tempuri.org/IConversionService/CelsiusAKelvinResponse")]
        double CelsiusAKelvin(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusAKelvin", ReplyAction="http://tempuri.org/IConversionService/CelsiusAKelvinResponse")]
        System.Threading.Tasks.Task<double> CelsiusAKelvinAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusARankine", ReplyAction="http://tempuri.org/IConversionService/CelsiusARankineResponse")]
        double CelsiusARankine(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusARankine", ReplyAction="http://tempuri.org/IConversionService/CelsiusARankineResponse")]
        System.Threading.Tasks.Task<double> CelsiusARankineAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusAReaumur", ReplyAction="http://tempuri.org/IConversionService/CelsiusAReaumurResponse")]
        double CelsiusAReaumur(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusAReaumur", ReplyAction="http://tempuri.org/IConversionService/CelsiusAReaumurResponse")]
        System.Threading.Tasks.Task<double> CelsiusAReaumurAsync(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/FahrenheitACelsius", ReplyAction="http://tempuri.org/IConversionService/FahrenheitACelsiusResponse")]
        double FahrenheitACelsius(double valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/FahrenheitACelsius", ReplyAction="http://tempuri.org/IConversionService/FahrenheitACelsiusResponse")]
        System.Threading.Tasks.Task<double> FahrenheitACelsiusAsync(double valor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConversionServiceChannel : _02.CLIWEB.ConversionServiceReference.IConversionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConversionServiceClient : System.ServiceModel.ClientBase<_02.CLIWEB.ConversionServiceReference.IConversionService>, _02.CLIWEB.ConversionServiceReference.IConversionService {
        
        public ConversionServiceClient() {
        }
        
        public ConversionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConversionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string usuario, string password) {
            return base.Channel.Login(usuario, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string usuario, string password) {
            return base.Channel.LoginAsync(usuario, password);
        }
        
        public double MetroAPie(double valor) {
            return base.Channel.MetroAPie(valor);
        }
        
        public System.Threading.Tasks.Task<double> MetroAPieAsync(double valor) {
            return base.Channel.MetroAPieAsync(valor);
        }
        
        public double KilometroAMilla(double valor) {
            return base.Channel.KilometroAMilla(valor);
        }
        
        public System.Threading.Tasks.Task<double> KilometroAMillaAsync(double valor) {
            return base.Channel.KilometroAMillaAsync(valor);
        }
        
        public double CentimetroAPulgada(double valor) {
            return base.Channel.CentimetroAPulgada(valor);
        }
        
        public System.Threading.Tasks.Task<double> CentimetroAPulgadaAsync(double valor) {
            return base.Channel.CentimetroAPulgadaAsync(valor);
        }
        
        public double PulgadaACentimetro(double valor) {
            return base.Channel.PulgadaACentimetro(valor);
        }
        
        public System.Threading.Tasks.Task<double> PulgadaACentimetroAsync(double valor) {
            return base.Channel.PulgadaACentimetroAsync(valor);
        }
        
        public double PieAMetro(double valor) {
            return base.Channel.PieAMetro(valor);
        }
        
        public System.Threading.Tasks.Task<double> PieAMetroAsync(double valor) {
            return base.Channel.PieAMetroAsync(valor);
        }
        
        public double KilogramoALibra(double valor) {
            return base.Channel.KilogramoALibra(valor);
        }
        
        public System.Threading.Tasks.Task<double> KilogramoALibraAsync(double valor) {
            return base.Channel.KilogramoALibraAsync(valor);
        }
        
        public double GramoAOnza(double valor) {
            return base.Channel.GramoAOnza(valor);
        }
        
        public System.Threading.Tasks.Task<double> GramoAOnzaAsync(double valor) {
            return base.Channel.GramoAOnzaAsync(valor);
        }
        
        public double ToneladaAKilogramo(double valor) {
            return base.Channel.ToneladaAKilogramo(valor);
        }
        
        public System.Threading.Tasks.Task<double> ToneladaAKilogramoAsync(double valor) {
            return base.Channel.ToneladaAKilogramoAsync(valor);
        }
        
        public double LibraAKilogramo(double valor) {
            return base.Channel.LibraAKilogramo(valor);
        }
        
        public System.Threading.Tasks.Task<double> LibraAKilogramoAsync(double valor) {
            return base.Channel.LibraAKilogramoAsync(valor);
        }
        
        public double OnzaAGramo(double valor) {
            return base.Channel.OnzaAGramo(valor);
        }
        
        public System.Threading.Tasks.Task<double> OnzaAGramoAsync(double valor) {
            return base.Channel.OnzaAGramoAsync(valor);
        }
        
        public double CelsiusAFahrenheit(double valor) {
            return base.Channel.CelsiusAFahrenheit(valor);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusAFahrenheitAsync(double valor) {
            return base.Channel.CelsiusAFahrenheitAsync(valor);
        }
        
        public double CelsiusAKelvin(double valor) {
            return base.Channel.CelsiusAKelvin(valor);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusAKelvinAsync(double valor) {
            return base.Channel.CelsiusAKelvinAsync(valor);
        }
        
        public double CelsiusARankine(double valor) {
            return base.Channel.CelsiusARankine(valor);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusARankineAsync(double valor) {
            return base.Channel.CelsiusARankineAsync(valor);
        }
        
        public double CelsiusAReaumur(double valor) {
            return base.Channel.CelsiusAReaumur(valor);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusAReaumurAsync(double valor) {
            return base.Channel.CelsiusAReaumurAsync(valor);
        }
        
        public double FahrenheitACelsius(double valor) {
            return base.Channel.FahrenheitACelsius(valor);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitACelsiusAsync(double valor) {
            return base.Channel.FahrenheitACelsiusAsync(valor);
        }
    }
}
